apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring-stack
    meta.helm.sh/release-namespace: default
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: monitoring-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 60.3.0
    chart: kube-prometheus-stack-60.3.0
    heritage: Helm
    release: monitoring-stack
  name: monitoring-slo-nginx-mysql.rules
  namespace: default
spec:
  groups:
    - name: sloth-slo-sli-recordings-mywebsite-nginx-SLO-requests-availability-nginx
      rules:
        - record: slo:sli_error:ratio_rate5m
          expr: |
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata",code=~"(5..|429)"}[5m])))
            /
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata"}[5m])))
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            sloth_window: 5m
            tier: "2"
        - record: slo:sli_error:ratio_rate30m
          expr: |
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata",code=~"(5..|429)"}[30m])))
            /
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata"}[30m])))
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            sloth_window: 30m
            tier: "2"
        - record: slo:sli_error:ratio_rate1h
          expr: |
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata",code=~"(5..|429)"}[1h])))
            /
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata"}[1h])))
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            sloth_window: 1h
            tier: "2"
        - record: slo:sli_error:ratio_rate2h
          expr: |
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata",code=~"(5..|429)"}[2h])))
            /
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata"}[2h])))
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            sloth_window: 2h
            tier: "2"
        - record: slo:sli_error:ratio_rate6h
          expr: |
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata",code=~"(5..|429)"}[6h])))
            /
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata"}[6h])))
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            sloth_window: 6h
            tier: "2"
        - record: slo:sli_error:ratio_rate1d
          expr: |
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata",code=~"(5..|429)"}[1d])))
            /
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata"}[1d])))
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            sloth_window: 1d
            tier: "2"
        - record: slo:sli_error:ratio_rate3d
          expr: |
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata",code=~"(5..|429)"}[3d])))
            /
            (sum(rate(promhttp_metric_handler_requests_total{job="nginxdata"}[3d])))
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            sloth_window: 3d
            tier: "2"
        - record: slo:sli_error:ratio_rate30d
          expr: |
            sum_over_time(slo:sli_error:ratio_rate5m{sloth_id="mywebsite-nginx-SLO-requests-availability-nginx", sloth_service="mywebsite-nginx-SLO", sloth_slo="requests-availability-nginx"}[30d])
            / ignoring (sloth_window)
            count_over_time(slo:sli_error:ratio_rate5m{sloth_id="mywebsite-nginx-SLO-requests-availability-nginx", sloth_service="mywebsite-nginx-SLO", sloth_slo="requests-availability-nginx"}[30d])
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            sloth_window: 30d
            tier: "2"

    - name: sloth-slo-meta-recordings-mywebsite-nginx-SLO-requests-availability-nginx
      rules:
        - record: slo:objective:ratio
          expr: vector(0.9990000000000001)
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            tier: "2"
        - record: slo:error_budget:ratio
          expr: vector(1-0.9990000000000001)
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            tier: "2"
        - record: slo:time_period:days
          expr: vector(30)
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            tier: "2"
        - record: slo:current_burn_rate:ratio
          expr: |
            slo:sli_error:ratio_rate5m{sloth_id="mywebsite-nginx-SLO-requests-availability-nginx", sloth_service="mywebsite-nginx-SLO", sloth_slo="requests-availability-nginx"}
            / on(sloth_id, sloth_slo, sloth_service) group_left
            slo:error_budget:ratio{sloth_id="mywebsite-nginx-SLO-requests-availability-nginx", sloth_service="mywebsite-nginx-SLO", sloth_slo="requests-availability-nginx"}
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            tier: "2"
        - record: slo:current_burn_rate_per_minute:ratio
          expr: |
            (slo:sli_error:ratio_rate5m{sloth_id="mywebsite-nginx-SLO-requests-availability-nginx", sloth_service="mywebsite-nginx-SLO", sloth_slo="requests-availability-nginx"}
            / on(sloth_id, sloth_slo, sloth_service) group_left
            slo:error_budget:ratio{sloth_id="mywebsite-nginx-SLO-requests-availability-nginx", sloth_service="mywebsite-nginx-SLO", sloth_slo="requests-availability-nginx"}) / 5
          labels:
            owner: devOpsteam
            repo: myorg/myservice
            sloth_id: mywebsite-nginx-SLO-requests-availability-nginx
            sloth_service: mywebsite-nginx-SLO
            sloth_slo: requests-availability-nginx
            tier: "2"

    - name: mywebsitenginxHighErrorRate
      rules:
        - alert: mywebsitenginxHighErrorRate
          expr: |
            avg(slo:sli_error:ratio_rate5m{job="nginxdata", sloth_slo="requests-availability-nginx", sloth_service="mywebsite-nginx-SLO", sloth_id="mywebsite-nginx-SLO-requests-availability-nginx"}) > 0.01
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High Error Rate for Nginx"
            description: "High error rate detected in Nginx service."

    - name: mywebsitenginxHighLatency
      rules:
        - alert: mywebsitenginxHighLatency
          expr: |
            avg(slo:sli_error:ratio_rate5m{job="nginxdata", sloth_slo="requests-availability-nginx", sloth_service="mywebsite-nginx-SLO", sloth_id="mywebsite-nginx-SLO-requests-availability-nginx"}) > 0.05
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High Latency for Nginx"
            description: "High latency detected in Nginx service."
