version: "prometheus/v1"
service: "mywebsite-nginx-SLO"
labels:
  owner: "devOpsteam"
  repo: "myorg/myservice"
  tier: "2"
slos:
  # Availability SLO for NGINX
  - name: "requests-availability-nginx"
    objective: 99.9
    description: "Common SLO based on availability for HTTP request responses of nginx."
    sli:
      events:
        error_query: sum(rate(promhttp_metric_handler_requests_total{job="nginxdata",code=~"(5..|429)"}[{{.window}}]))
        total_query: sum(rate(promhttp_metric_handler_requests_total{job="nginxdata"}[{{.window}}]))
    alerting:
      name: mywebsitenginxHighErrorRate
      labels:
        category: "availability"
      annotations:
        summary: "High error rate on 'mywebsite-nginx' requests responses"
      page_alert:
        labels:
          severity: pageteam
          routing_key: myteam
      ticket_alert:
        labels:
          severity: "slack"
          slack_channel: "#alerts-myteam"

